### ISSUE TITLE
Bug when working with global template directory

### ISSUE THREAD

**Issue by oliverandrich** [carltongibson/notes#26]
The following line of code is, from my perspective, a bug. It is meant to handle `settings.TEMPLATES[0]["DIRS"]`, which is defined as list in the [Django documentation](https://docs.djangoproject.com/en/4.2/ref/settings/#dirs). But the method `list_template_files` only works successfully when a single path is given in call.

https://github.com/carltongibson/notes/blob/f4a6678be73faa348adb466306faf762ba2eb316/source/tailwind/django-integration.md?plain=1#L55

As `settings.TEMPLATES[0]["DIRS"]` is defined as array, I like to suggest the following changes.

```python
for template_dir in settings.TEMPLATES[0]["DIRS"]:
    template_files += self.list_template_files(template_dir)
```

**Comment by carltongibson** [comment]
Thanks @oliverandrich! 

(All the projects I've been using this with leverage the [Single Folder Layout](https://noumenal.es/notes/django/single-folder-layout/), just with an app-level dir, so that's why I didn't hit this. 🤦‍♀️)
